
[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
dependencies = [
    "python-telegram-bot>=20.7",
    "psycopg2-binary>=2.9.9",
    "pytz>=2023.3",
]
requires-python = ">=3.11"
